#' Demographic Dataset - Neuro
#'
#' An updated SDTM DM dataset subset with age appropriate Alzheimer's Disease patients
#' @keywords datasets
#' @family datasets
"dm_neuro"

# This file is automatically generated by data-raw/nv_neuro.R.
# Please rerun nv_enuro.R to create it again.
# Manual edits are not recommended, as changes may be overwritten.
#' Nervous System Findings Dataset
#'
#' A SDTM NV domain dataset for Alzheimer's disease observational and interventional studies, including amyloid and tau PET data at baseline and two follow-up visits reflect levels of pathology appropriate for disease or treatment course
#' @keywords datasets
#' @family datasets
#'
#' @name nv_neuro
#' @title Nervous System Findings Dataset
#' @description A SDTM NV domain dataset containing nervous system findings and measurements
#' @docType data
#' @format A data frame with 20 columns:
#'   \describe{
#'     \item{STUDYID}{Study Identifier}
#'     \item{DOMAIN}{Domain Abbreviation}
#'     \item{USUBJID}{Unique Subject Identifier}
#'     \item{NVSEQ}{Sequence Number}
#'     \item{NVLNKID}{Link ID}
#'     \item{NVTESTCD}{Short Name of Nervous System Test}
#'     \item{NVTEST}{Name of Nervous System Test}
#'     \item{NVCAT}{Category for Nervous System Test}
#'     \item{NVLOC}{Location Used for the Measurement}
#'     \item{NVMETHOD}{Method of Test or Examination}
#'     \item{NVNAM}{Vendor Name}
#'     \item{NVORRES}{Result or Finding in Original Units}
#'     \item{NVORRESU}{Original Units}
#'     \item{NVSTRESC}{Character Result/Finding in Std Format}
#'     \item{NVSTRESN}{Numeric Result/Finding in Standard Units}
#'     \item{NVSTRESU}{Standard Units}
#'     \item{VISITNUM}{Visit Number}
#'     \item{VISIT}{Visit Name}
#'     \item{NVDTC}{Date/Time of Collection}
#'     \item{NVDY}{Study Day of Collection}
#'     \item{NVLOBXFL}{Last Observation Before Exposure Flag}
#'   }
#'
#' @source Constructed using `dm_neuro` from `{admiralneuro}` package for USUBJID and cohort information, `vs` from `{pharmaversesdtm}` for visit schedule such as VISIT, NVDTC, NVDY
"nv_neuro"

# This file is automatically generated by data-raw/suppnv_neuro.R
# Please rerun suppnv_neuro.R to create it again.
# Manual edits are not recommended, as changes may be overwritten.
#' Supplemental Nervous System Findings Dataset
#'
#' A SDTM SUPPNV domain dataset
#' @keywords datasets
#' @family datasets
#'
#' @name suppnv_neuro
#' @title Supplemental Nervous System Findings Dataset
#' @description A SDTM SUPPNV domain dataset containing reference regions used for SUVR calculation
#' @docType data
#' @format A data frame with 8 columns:
#'  \describe{
#'   \item{STUDYID}{Study Identifier}
#'   \item{RDOMAIN}{Related Domain Abbreviation}
#'   \item{USUBJID}{Unique Subject Identifier}
#'   \item{IDVAR}{Identifying Variable}
#'   \item{IDVARVAL}{Identifying Variable Value}
#'   \item{QNAM}{Qualifier Variable Name}
#'   \item{QLABEL}{Qualifier Variable Label}
#'   \item{QVAL}{Data Value}
#'   \item{QORIG}{Origin}
#'   \item{QEVAL}{Evaluator}
#'   }
#' @source Constructed using `nv_neuro` from `{admiralneuro}` package
"suppnv_neuro"

# This file is automatically generated by data-raw/ag_neuro.R
# Please rerun ag_neuro.R to create it again.
# Manual edits are not recommended, as changes may be overwritten.
#' Procedure Agents for Nervous System Dataset
#'
#' A SDTM AG domain dataset
#' @keywords datasets
#' @family datasets
#'
#' @name ag_neuro
#' @title Procedure Agents for Nervous System Dataset
#' @description A SDTM AG domain dataset containing procedure agents for nervous system
#' @docType data
#' @format A data frame with 12 columns:
#' \describe{
#'  \item{STUDYID}{Study Identifier}
#'  \item{DOMAIN}{Domain Abbreviation}
#'  \item{USUBJID}{Unique Subject Identifier}
#'  \item{AGSEQ}{Sequence Number}
#'  \item{AGTRT}{Reported Agent Name}
#'  \item{AGCAT}{Category for Category}
#'  \item{AGDOSE}{Dose per Administration}
#'  \item{AGDOSEU}{Dose Units}
#'  \item{AGROUTE}{Route of Administration}
#'  \item{AGLNKID}{Link ID}
#'  \item{VISITNUM}{Visit Number}
#'  \item{VISIT}{Visit Name}
#'  \item{AGSTDTC}{Start Date/Time of Agent}
#'  }
#' @source Constructed using `nv_neuro` from `{admiralneuro}` package
"ag_neuro"

#' @name lb_neuro
#' @title Laboratory Test Results for Nervous System Dataset
#' @description A SDTM LB domain dataset containing laboratory test results for Alzheimer's Disease studies,
#' specifically Alpha-synuclein Seed Amplification Assay (SAA) results from cerebrospinal fluid (CSF) samples.
#' The dataset includes baseline assessments with positive rates varying by treatment group.
#' @docType data
#' @format A data frame with 23 columns:
#' \describe{
#'  \item{STUDYID}{Study Identifier}
#'  \item{DOMAIN}{Domain Abbreviation}
#'  \item{USUBJID}{Unique Subject Identifier}
#'  \item{LBSEQ}{Sequence Number}
#'  \item{LBTESTCD}{Lab Test or Examination Short Name}
#'  \item{LBTEST}{Lab Test or Examination Name}
#'  \item{LBCAT}{Category for Lab Test}
#'  \item{LBORRES}{Result or Finding in Original Units}
#'  \item{LBORRESU}{Original Units}
#'  \item{LBORNRLO}{Reference Range Lower Limit in Orig Unit}
#'  \item{LBORNRHI}{Reference Range Upper Limit in Orig Unit}
#'  \item{LBSTRESC}{Character Result/Finding in Std Format}
#'  \item{LBSTRESN}{Numeric Result/Finding in Standard Units}
#'  \item{LBSTRESU}{Standard Units}
#'  \item{LBSTNRLO}{Reference Range Lower Limit-Std Units}
#'  \item{LBSTNRHI}{Reference Range Upper Limit-Std Units}
#'  \item{LBNRIND}{Reference Range Indicator}
#'  \item{LBBLFL}{Baseline Flag}
#'  \item{VISITNUM}{Visit Number}
#'  \item{VISIT}{Visit Name}
#'  \item{VISITDY}{Planned Study Day of Visit}
#'  \item{LBDTC}{Date/Time of Specimen Collection}
#'  \item{LBDY}{Study Day of Specimen Collection}
#'  }
#' @details
#' The dataset contains Alpha-synuclein Seed Amplification Assay (ASYNASAA) results
#' categorized as "Positive" or "Negative". Results are generated with treatment-specific
#' positive rates: 30% for placebo/control group across all visits, and 30% at baseline
#' for treatment group. The dataset is structured to support analysis of biomarker status
#' in Alzheimer's Disease clinical trials.
#' @source Constructed using `dm_neuro`, `nv_neuro`, and `adsl_neuro` from `{admiralneuro}` package,
#' along with `ex` from `{pharmaversesdtm}` package
"lb_neuro"

#' Amyloid PET Scan Analysis Dataset - Neuro
#'
#' An updated ADaM ADAPET dataset using NV, AG, SUPPNV, ADSL
#' @keywords datasets
#' @family datasets
"admiralneuro_adapet"

#' Tau PET Scan Analysis Dataset - Neuro
#'
#' An updated ADaM ADTPET dataset using NV, AG, SUPPNV, ADSL
#' @keywords datasets
#' @family datasets
"admiralneuro_adtpet"

#' Subject Level Analysis Dataset-updated
#'
#' An updated ADaM ADSL dataset with Alzheimer's Disease patients
#' @keywords datasets
#' @family datasets
"adsl_neuro"
